### ISSUE TITLE
Кастомайзер мешает загрузке содержимого страницы

### ISSUE THREAD

**Issue by denezhkin** [sbis-team/ui-customizer#8]
Вчера 12.10.17 в районе 16:00 МСК неожиданно перестало грузиться содержимое страницы https://test-online.sbis.ru/contragents.html на тестовом стенде. Только левый аккордеон и шапка.
Сконвертил ресурсы - то же. Раскатал новый дистрибутив - то же. Сегодня утром выяснил, что проблема в скрипте кастомайзера.
P.S. еще в карточке задачи/ошибки куда-то отвалилась кнопка [forkname] создания названия ветки.

**Comment by denezhkin** [comment]
Проблема ушла после выключения-включения скрипта.

**Comment by IgorNovozhilov** [comment]
Были похожие проблемы, я все поправил к версии 1.3.6.
После обновления не повторяется?
Это проявлялось только на локальном стенде?
P.S. из за описанной проблемы могли слететь опции, проверь настройки.

**Comment by denezhkin** [comment]
Обновил до 1.3.6. Повторяется. Только на локальном.
![image](https://user-images.githubusercontent.com/7950505/31601973-4124732c-b264-11e7-8ff6-2c7880c82753.png)
Кнопка формирования имени ветки действительно слетело в настройках.

**Comment by IgorNovozhilov** [comment]
А какой он у тебя версии?

**Comment by denezhkin** [comment]
Стенд 3.17.210 от 11-12 октября. Свежий)

**Comment by IgorNovozhilov** [comment]
Похоже для локальных стендов не подъехали правки по отказу от оглавления, видимо они в sdk...

**Comment by IgorNovozhilov** [comment]
https://github.com/sbis-team/ui-customizer/blob/release/CHANGELOG.md#Обновление-v137

**Comment by denezhkin** [comment]
Спасибо! Теперь всё работает.
